"""
engine.py
----------
Decision Fusion Engine — main orchestrator.

Wires together:
  Gates → Aggregator → Conflict Resolver → Score → FusionScore

One candidate in, one FusionScore out.
No ranking logic lives here — that belongs in ranker.py.
"""

from __future__ import annotations

import logging
from typing import Optional

from src.decision.models import PolicyResult
from src.features.intelligence_models import CandidateIntelligence
from src.job_intelligence.models import JobIntent
from src.evidence.models import EvidenceGraph

from src.fusion.models import (
    FusionScore,
    GateResult,
    TIER_1,
    TIER_2,
    TIER_3,
    TIER_GATE,
)
from src.fusion.gates import evaluate_gates
from src.fusion.aggregator import (
    compute_anchor_scores,
    compute_tier_score,
    assign_tier,
    compute_booster_scores,
    compute_booster_total,
    compute_response_multiplier,
    compute_fusion_score,
)
from src.fusion.resolver import resolve_conflicts

logger = logging.getLogger(__name__)


class DecisionFusionEngine:
    """
    Combines 8 independent policy results into a single,
    explainable FusionScore for one candidate.

    Usage:
        engine = DecisionFusionEngine()
        score = engine.fuse(intel, policy_results, job_intent)
    """

    def fuse(
        self,
        intel: CandidateIntelligence,
        policy_results: list,
        job_intent: Optional[JobIntent] = None,
    ) -> FusionScore:
        """
        Produce a FusionScore for one candidate.

        Steps:
        1. Evaluate hard gates
        2. Compute anchor scores and tier
        3. Compute booster scores
        4. Compute response multiplier
        5. Resolve conflicts (may adjust tier and booster)
        6. Compute final fusion score
        7. Package into FusionScore with full explainability
        """
        result = FusionScore(
            candidate_id=intel.candidate_id,
            candidate_name=intel.name,
        )

        # Step 1: Hard gates
        gate_result = evaluate_gates(policy_results, intel)
        result.gate_result = gate_result

        if not gate_result.passed:
            result.tier = TIER_GATE
            result.fusion_score = 0.0
            result.reasoning = (
                f"Gate failure(s): {'; '.join(gate_result.failed_gates)}"
            )
            logger.debug(
                "Gate failed for %s: %s",
                intel.candidate_id,
                gate_result.failed_gates,
            )
            return result

        # Step 2: Anchor scores and tier
        anchor_scores = compute_anchor_scores(policy_results)
        tier_score = compute_tier_score(anchor_scores)
        tier = assign_tier(tier_score)

        result.anchor_scores = anchor_scores

        # Step 3: Booster scores
        booster_scores = compute_booster_scores(policy_results)
        booster_total = compute_booster_total(booster_scores)

        result.booster_scores = booster_scores

        # Step 4: Response multiplier
        response_multiplier = compute_response_multiplier(intel)
        result.response_multiplier = response_multiplier

        # Step 5: Conflict resolution
        (
            resolved_tier,
            resolved_tier_score,
            resolved_booster,
            resolutions,
        ) = resolve_conflicts(
            policy_results,
            intel,
            tier,
            tier_score,
            booster_total,
        )

        result.tier = resolved_tier
        result.tier_score = resolved_tier_score
        result.booster_score = resolved_booster
        result.conflicts_resolved = resolutions

        # Step 6: Final fusion score
        fusion_score = compute_fusion_score(
            resolved_tier_score,
            resolved_booster,
            response_multiplier,
        )
        result.fusion_score = fusion_score

        # Step 7: Brief reasoning note
        result.reasoning = _build_reasoning(
            intel, result, anchor_scores, resolutions
        )

        logger.debug(
            "%s | tier=%s | score=%.4f | anchors=%s",
            intel.candidate_id,
            resolved_tier,
            fusion_score,
            {k: round(v, 2) for k, v in anchor_scores.items()},
        )

        return result


def _build_reasoning(
    intel: CandidateIntelligence,
    result: FusionScore,
    anchor_scores: dict,
    resolutions: list,
) -> str:
    """
    Build a one-paragraph deterministic reasoning note.
    Full explanation is generated by reasoning.py in Phase 5B.
    This is the lightweight inline version.
    """
    parts = []

    parts.append(
        f"{intel.name or intel.candidate_id} placed in {result.tier} "
        f"(fusion score {result.fusion_score:.4f})."
    )

    weakest_anchor = min(anchor_scores, key=anchor_scores.get)
    strongest_anchor = max(anchor_scores, key=anchor_scores.get)

    parts.append(
        f"Strongest signal: {strongest_anchor} "
        f"({anchor_scores[strongest_anchor]:.2f}). "
        f"Limiting factor: {weakest_anchor} "
        f"({anchor_scores[weakest_anchor]:.2f})."
    )

    if resolutions:
        conflict_names = [r.conflict_type for r in resolutions]
        parts.append(
            f"Conflict(s) resolved: {', '.join(conflict_names)}."
        )

    if result.response_multiplier < 0.80:
        parts.append(
            f"Response rate multiplier applied: "
            f"{result.response_multiplier:.2f} "
            f"(low platform engagement detected)."
        )

    return " ".join(parts)


def fuse_batch(
    intelligence_list: list,
    policy_results_map: dict,
    job_intent: Optional[JobIntent] = None,
    log_every: int = 100,
) -> list:
    """
    Run fusion for all candidates.

    Args:
        intelligence_list: List[CandidateIntelligence]
        policy_results_map: dict mapping candidate_id -> List[PolicyResult]
        job_intent: Optional JobIntent for context

    Returns:
        List[FusionScore]
    """
    engine = DecisionFusionEngine()
    results = []

    for i, intel in enumerate(intelligence_list, start=1):
        policy_results = policy_results_map.get(intel.candidate_id, [])
        try:
            score = engine.fuse(intel, policy_results, job_intent)
            results.append(score)
        except Exception as e:
            logger.error(
                "Fusion failed for %s: %s", intel.candidate_id, e
            )

        if i % log_every == 0:
            logger.info("Fusion progress: %d / %d", i, len(intelligence_list))

    logger.info("Fusion complete: %d candidates processed", len(results))
    return results
